### ISSUE TITLE
Tensorflow 2 compatibility

### ISSUE THREAD

**Issue by James-Large** [sktime/sktime-dl#16]
Brought up initially in #15 

TF2 compatibility is definitely something to look into. I'm not sure how big of a job it would be for this repo in particular. Presumably the [automated upgrade process](https://blog.tensorflow.org/2019/02/upgrading-your-code-to-tensorflow-2-0.html) could be applied, though from memory there's very little raw tensorflow code used anyway

Open question of whether to _enforce_ version >=2, or if there are still reasons related to implementation maturity/stability to allow 1.x

**Comment by Withington** [comment]
Feel free to assign this to me.

The automated upgrade process highlighted only one possible issue (below) but it is not an issue for sktime-dl because it is using keras, not tf.keras.

__sktime_dl/classifiers/deeplearning/_base.py:103:16 [and 105:16]: WARNING: *.save requires manual check. (This warning is only applicable if the code saves a tf.Keras model). Keras model.save now saves to the Tensorflow SavedModel format by default, instead of HDF5. To continue saving to HDF5, add the argument save_format='h5' to the save() function._

I'll add a tf2 env to the Travis build matrix and create a PR in the next couple of days. This will help answer the stability question.

**Comment by James-Large** [comment]
Covered in #25
