### ISSUE TITLE
Migrate to tf.keras

### ISSUE THREAD

**Issue by Withington** [sktime/sktime-dl#21]
**Is your feature request related to a problem? Please describe.**
Consider migrating from keras to TensorFlow keras (tf.keras).

Keras will only be maintained until April 2020 and the advice from [keras-team](https://github.com/keras-team/keras#multi-backend-keras-and-tfkeras) is to migrate to tf.keras. Although keras 2.3 supports TensorFlow 2, it doesn't use tf2's new features, such as eager execution.

Migrating from keras to tf.keras means losing multi-backend support, i.e. Theano and CNTK, but the other backends are no longer in active development (ref. [Theano](https://groups.google.com/forum/#!msg/theano-users/7Poq8BZutbY/rNCIfvAEAwAJ); [CNTK](https://docs.microsoft.com/en-us/cognitive-toolkit/releasenotes/cntk_2_7_release_notes)).

**Describe the solution you'd like**
Feel free to assign this issue to me. 
+ Change  ```import keras``` to ```from tensorflow import keras```
+ Test
+ Update README

**Describe alternatives you've considered**
Do nothing: Not migrating means not being able to use future keras (now tf.keras) developments. Moreover, keras is only compatible with Python<=3.6 and this will restrict sktime-dl going forward.

**Additional context**
Additional benefit - migrating from keras to tf.keras will also enable migration from keras-contrib (which isn't on PyPi) to tensorflow-addons. This package is used in sktime-dl to provide keras_contrib.layers.InstanceNormalization()

**Comment by Withington** [comment]
Feel free to assign this issue to me if you would indeed like to migrate to tf.keras

**Comment by mloning** [comment]
Sounds reasonable to me, any objections @James-Large?

**Comment by James-Large** [comment]
Apologies, seems like I'm not getting notifications for this repo anymore, maybe since the org change. 

Yes I think this is a good idea for future proofing and allowing for passive speed ups/stability improvements via updates to tf and tf.keras as mentioned

iirc essentially the only change in terms of usage is pretty much just the import statement? And some Session code if needed

I'm on placement at the moment doing a lot of away-from-keyboard work, but will try harder to be responsive over the next couple of months, and implement some of my own things.

**Comment by Withington** [comment]
Yes - the change is pretty much just the import statement. Plus a similar change to import tf.addons in place of keras-contrib.

**Comment by James-Large** [comment]
Covered in #25
