### ISSUE TITLE
Creating a docker image for sktime-dl

### ISSUE THREAD

**Issue by James-Large** [sktime/sktime-dl#27]
This certainly seems a prudent next step in aiding usage/setup, particularly for non-expert users 

Or any alternative/similar systems to use instead? I noticed while setting this issue up that sktime has a neat binder plugin on the readme, worth investigating for sktime-dl too @mloning?

**Comment by Withington** [comment]
Docker gets my vote, it is what [TensorFlow recommends](https://www.tensorflow.org/install/gpu) for GPU support.

What Docker containers do we need? One that launches Jupyter and/or one that runs all the tests? 

We could also add an "Open in Colab" button to the README and have it open an example Notebook. Like this 
[![Run model (open In Colab)](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/notebooks/intro.ipynb)
The user can select to use a GPU in Colab via the Runtime option.

**Comment by Withington** [comment]
Started work on this in my [fork](https://github.com/Withington/sktime-dl/tree/docker_examples).

Plan

- Docker container to run tests on GPU - done
- Docker container to launch Jupyter with sktime-dl
- Example notebook to run in the Docker container (re. #26 )

**Comment by mloning** [comment]
I like the colab button, we use binder for base sktime, but colab makes sense for this repo. Can you launch it in the examples folder in case we want to include multiple notebooks?

**Comment by Withington** [comment]
We can put Open in Colab buttons anywhere, even in the notebooks themselves.  We can choose which notebook each button opens. The button is aimed at opening one notebook in Colab, rather than a folder. It’s easy enough to make a folder full of notebooks available in Colab though, it’s well integrated with GitHub.

The idea would be to open an example notebook in Colab and ```!pip install sktime-dl``` from pypi. I’ll demo that once we have a new release in pypi. Is binder the same or does that install code from your GitHub branch?

**Comment by mloning** [comment]
For Binder, you leave a requirements file in the repo and based on that Binder launches a VM.

**Comment by Withington** [comment]
That sounds good. I’ll try both.

**Comment by mloning** [comment]
Closed by #35
